//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PayId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public string AmountToPay { get; set; }
        public string Paid { get; set; }
        public string PendingAmount { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
